---
apiVersion: v1
kind: Service
metadata:
  name: mini-server-1
spec:
  selector:
    app: mini-server-1

  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata: {name: mini-server-1}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-server-1
      track: stable
  strategy:
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: mini-server-1
        track: stable
      name: mini-server-1
    spec:
      containers:
      - image: mosarvit/k8s_mini_server_1
        imagePullPolicy: IfNotPresent
        name: mini-server-1
        resources:
          limits:
            memory: 0.25G
            cpu: 0.25
        terminationMessagePath: /dev/termination-log
      - image: mosarvit/k8s_mini_server_2
        imagePullPolicy: IfNotPresent
        name: mini-server-2
        resources:
          limits:
            memory: 0.25G
            cpu: 0.25
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
    
---
apiVersion: v1
kind: Service
metadata:
  name: mini-server-3
spec:
  selector:
    app: mini-server-3

  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata: {name: mini-server-3}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-server-3
      track: stable
  strategy:
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: mini-server-3
        track: stable
      name: mini-server-3
    spec:
      containers:
      - image: mosarvit/k8s_mini_server_3
        imagePullPolicy: IfNotPresent
        name: mini-server-3
        resources:
          limits:
            memory: 0.25G
            cpu: 0.25
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
